#!/bin/bash

if [[ $# -ne 1 ]]; then
    echo "Usage: vcf_peekinfo <vcf>"
fi

nbr=$(zgrep -v "#" $1 | head -1 | cut -f8 | tr ";" "\n" | grep -v CSQ | wc -l)
echo "INFO fields (excluding CSQ): ${nbr}"
zgrep -v "#" $1 | head -1 | cut -f8 | tr ";" "\n" | grep -v CSQ | tr "=" "\t" | column -s$'\t' -t 
