#!/bin/bash

if [[ $# -ne 1 && $# -ne 2 && $# -ne 3 ]]; then
    echo "Usage: vcf_head <vcf> [n] [keephead]"
fi

if [[ $# -eq 1 ]]; then
    zgrep -v "^#" $1 | head -5
fi

if [[ $# -eq 2 ]]; then
    zgrep -v "^#" $1 | head -$2
fi

if [[ $# -eq 3 ]]; then
    zgrep "^#" $1
    zgrep -v "^#" $1 | head -$2
fi
