#!/bin/bash

if [[ $# -ne 1 && $# -ne 2 ]]; then
    echo "Usage: vcf_peekinfo <vcf> [<filter>]"
fi

filter_pattern=""
if [[ $# -eq 2 ]]; then
    filter_pattern=$2
fi

target_line=$(zgrep -v "#" $1 | grep -P "${filter_pattern}" | head -1)
chr=$(echo ${target_line} | cut -f1 -d" ")
pos=$(echo ${target_line} | cut -f2 -d" ")
ref=$(echo ${target_line} | cut -f3 -d" ")
var=$(echo ${target_line} | cut -f4 -d" ")
echo "${chr} ${pos} ${ref} ${var}"
nbr=$(echo ${target_line} | cut -f8 -d" " | tr ";" "\n" | grep -v CSQ | wc -l)
echo "INFO fields (excluding CSQ): ${nbr}"
echo ${target_line} | cut -f8 -d" " | tr ";" "\n" | grep -v CSQ | tr "=" "\t" | column -s$'\t' -t 

