#!/bin/bash

usage() {
    echo "Usage: vcf_get -f <vcf> -c <chr> [-s <startpos> [-e <endpos>]] [-l <line limit>] [-h]"
    echo "       vcf_get -f <vcf> -r <chr:startpos-endpos> [-l <line limit>] [-h]"
}

vcf=""
chr=""
startpos=""
endpos=""
include_header=false
line_limit=""

while getopts "f:c:s:e:r:hl:" opt; do
    case ${opt} in
        f) vcf="$OPTARG" ;;
        c) chr="$OPTARG" ;;
        s) startpos="$OPTARG" ;;
        e) endpos="$OPTARG" ;;
        r)
            chr="${OPTARG%:*}"
            range="${OPTARG#*:}"
            startpos="${range%-*}"
            endpos="${range#*-}"
            ;;
        h) include_header=true ;;
        l) line_limit="$OPTARG" ;;
        \?) usage ;;
    esac
done

if [[ -z ${vcf} || -z ${chr} ]]; then
    usage
fi

if [[ ${vcf} != *.vcf.gz ]]; then
    echo "The input file is expected to have .vcf.gz suffix"
fi

if [[ ! -f "${vcf}.tbi" && -f "${vcf}.csi" ]]; then
    echo "No index found, attempting to generate index..."
    tabix ${vcf}
fi

if ${include_header}; then
    zgrep "^#" ${vcf}
fi

echo "Limit '${line_limit}'"
if [[ -n "${startpos}" ]]; then
    if [[ -n "${line_limit}" ]]; then
        tabix ${vcf} "${chr}:${startpos}-${endpos}" | head -n ${line_limit}
    else
        tabix ${vcf} "${chr}:${startpos}-${endpos}"
    fi
else
    if [[ -n "${line_limit}" ]]; then
        tabix ${vcf} ${chr} | head -n ${line_limit}
    else
        echo "Chr '${chr}'"
        tabix ${vcf} "${chr}"
    fi
fi
